import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "@/components/Navbar";
import Resume from "@/components/Resume";

const InstrumentSans = Instrument_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InstrumentSans.className}>
        <Navbar />
        <div className="w-full flex">
          {children}
          <Resume />
        </div>
      </body>
    </html>
  );
}
