"use client";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Resume from "@/components/Resume";
import { usePDF } from "react-to-pdf";

const InstrumentSans = Instrument_Sans({ subsets: ["latin"], display: "swap" });

// export const metadata = {
//   title: "Resume Builder",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { toPDF, targetRef } = usePDF({ filename: "page.pdf" });

  return (
    <html lang="en">
      <body className={InstrumentSans.className}>
        <Navbar toPDF={toPDF} />
        <div className="w-full flex">
          {children}
          <Resume targetRef={targetRef} />
        </div>
      </body>
    </html>
  );
}
